channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - rdkit
  - rise
  - networkx
  - ase
  - nglview
  - tqdm
  - scikit-learn
  - ipython
  - ipywidgets
  - ipykernel
  - pip:
    - ase
    - torchani
