channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - rdkit
  - rise
  - networkx
  - ase
  - tqdm
  - scikit-learn
  - nodejs
  - ipython
  - ipywidgets=7.5.1
  - notebook
  - ipykernel
  - nglview=2.7
  - pip:
    - ase
    - torchani
